# core/logic/config.yaml

risk_calculation:
  radius: 250  # Radio (en metros) para buscar incidentes alrededor del nodo
  w_safety: 0.99  # Valor de prioridad de la seguridad (entre el 0 y el 1)
  gravedad_max: 5     # Valor m√°ximo esperado de gravedad (para normalizar)

incident_weights:
  asalto: 1.0
  choque: 0.7
  homicidio: 1.5
  robo: 0.8
  otro: 0.5
